name: salaryinfo
description: بوابة الموظف الرقمية - الشركة العامة لتعبئة وخدمات الغاز
publish_to: "none"

version: 1.0.14+27

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  http: ^1.1.0

  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.0
  webview_flutter_wkwebview: ^3.17.0

  google_fonts: 8.0.1

  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  device_info_plus: ^12.3.0
  permission_handler: ^12.0.1
  gal: ^2.3.2
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  flutter_local_notifications: ^20.1.0
  url_launcher: ^6.3.2
  package_info_plus: ^9.0.0
  provider: ^6.1.5+1
  connectivity_plus: ^7.0.0
  mysql1: ^0.20.0
  timeago: ^3.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
