name: salaryinfo
description: Ø¨ÙˆØ§Ø¨Ø© Ø§Ù„Ù…ÙˆØ¸Ù Ø§Ù„Ø±Ù‚Ù…ÙŠØ© - Ø§Ù„Ø´Ø±ÙƒØ© Ø§Ù„Ø¹Ø§Ù…Ø© Ù„ØªØ¹Ø¨Ø¦Ø© ÙˆØ®Ø¯Ù…Ø§Øª Ø§Ù„ØºØ§Ø²
publish_to: 'none'
version: 1.0.11+4

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # ğŸ”¥ Firebase Core
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  
  # WebView
  webview_flutter: ^4.4.2
  webview_flutter_android: ^2.12.2
  webview_flutter_wkwebview: ^2.16.2
  
  # UI & Design
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  
  # Storage & Permissions
  shared_preferences: ^2.2.2
  permission_handler: ^10.4.4
  device_info_plus: ^9.1.0
  gal: ^2.2.1
  path_provider: ^2.1.0
  
  # Utilities
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  
  # Other
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
  
  generate: true