name: salaryinfo
description: بوابة الموظف الرقمية - الشركة العامة لتعبئة وخدمات الغاز
publish_to: "none"

version: 1.0.11+6

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase (MINIMAL - NO CRASHLYTICS)
  firebase_core: ^2.27.0
  firebase_messaging: ^16.0.4

  # WebView
  webview_flutter: ^4.4.4

  # UI
  google_fonts: ^6.3.3

  # Storage
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
